export const productSeedData = [
  {
    name: "Women Round Neck Cotton Top",
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 100,
    imageFiles: ["p_img1.png"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: true,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 200,
    imageFiles: [
      "p_img2_1.png",
      "p_img2_2.png",
      "p_img2_3.png",
      "p_img2_4.png",
    ],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    bestseller: true,
  },
  {
    name: "Girls Round Neck Cotton Top",
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 220,
    imageFiles: ["p_img3.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "L", "XL"],
    bestseller: true,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 110,
    imageFiles: ["p_img4.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "XXL"],
    bestseller: true,
  },
  {
    name: "Women Round Neck Cotton Top",
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 130,
    imageFiles: ["p_img5.png"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    bestseller: true,
  },
  {
    name: "Girls Round Neck Cotton Top",
    description:
      "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
    price: 140,
    imageFiles: ["p_img6.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "L", "XL"],
    bestseller: true,
  },

  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 190,
    imageFiles: ["p_img7.png"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 140,
    imageFiles: ["p_img8.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 100,
    imageFiles: ["p_img9.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 110,
    imageFiles: ["p_img10.png"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 120,
    imageFiles: ["p_img11.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 150,
    imageFiles: ["p_img12.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 130,
    imageFiles: ["p_img13.png"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 160,
    imageFiles: ["p_img14.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 140,
    imageFiles: ["p_img15.png"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 170,
    imageFiles: ["p_img16.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 150,
    imageFiles: ["p_img17.png"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 180,
    imageFiles: ["p_img18.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 160,
    imageFiles: ["p_img19.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Palazzo Pants with Waist Belt",
    price: 190,
    imageFiles: ["p_img20.png"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 170,
    imageFiles: ["p_img21.png"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Palazzo Pants with Waist Belt",
    price: 200,
    imageFiles: ["p_img22.png"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 180,
    imageFiles: ["p_img23.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 210,
    imageFiles: ["p_img24.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 190,
    imageFiles: ["p_img25.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 220,
    imageFiles: ["p_img26.png"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Girls Round Neck Cotton Top",
    price: 200,
    imageFiles: ["p_img27.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 230,
    imageFiles: ["p_img28.png"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 210,
    imageFiles: ["p_img29.png"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 240,
    imageFiles: ["p_img30.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 220,
    imageFiles: ["p_img31.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 250,
    imageFiles: ["p_img32.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Girls Round Neck Cotton Top",
    price: 230,
    imageFiles: ["p_img33.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 260,
    imageFiles: ["p_img34.png"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 240,
    imageFiles: ["p_img35.png"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 270,
    imageFiles: ["p_img36.png"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Round Neck Cotton Top",
    price: 250,
    imageFiles: ["p_img37.png"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 280,
    imageFiles: ["p_img38.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Men Printed Plain Cotton Shirt",
    price: 260,
    imageFiles: ["p_img39.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 290,
    imageFiles: ["p_img40.png"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 270,
    imageFiles: ["p_img41.png"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 300,
    imageFiles: ["p_img42.png"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 280,
    imageFiles: ["p_img43.png"],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 310,
    imageFiles: ["p_img44.png"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 290,
    imageFiles: ["p_img45.png"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 320,
    imageFiles: ["p_img46.png"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 300,
    imageFiles: ["p_img47.png"],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 330,
    imageFiles: ["p_img48.png"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 310,
    imageFiles: ["p_img49.png"],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Kid Tapered Slim Fit Trouser",
    price: 340,
    imageFiles: ["p_img50.png"],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },

  {
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 320,
    imageFiles: ["p_img51.png"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
  {
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 350,
    imageFiles: ["p_img52.png"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: false,
  },
];
